name: Checks

on: pull_request

jobs:
  test:
    name: "Typechecking"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install NPM dependencies
        run: npm install

      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run Type Checking
        run: tsc
